baseURL = "https://www.easyolap.cn"
builddrafts                = false
languageCode               = "zh"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Frank Li's blog"

pygmentsuseclasses         = true

[author]
  name = "李在超"
  homepage = "https://www.easyolap.cn"

[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blogs"
    url                    = "blogs/"  

  [[menu.main]]
    name                   = "随笔"
    weight                 = -110
    identifier             = "publications"
    url                    = "publications/" 
    
  [[menu.main]]
    name                   = "简介"
    weight                 = -105
    identifier             = "resume"
    url                    = "resume/index.html" 
    
  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/index.html"  

 

[params]
  faviconfile              = "img/TechChat.jpg"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Frank Li"
  description              = ["Be myself.", "Love the wonderful world.", "Do the right things and be a better man."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ 超越永无止境！ ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "surpass_li@aliyun.com"
  github                   = "//github.com/surpass"
  linkedin                 = "https://www.linkedin.com/in/frank-li-a109b65a/"
#  facebook                 = "//facebook.com/you"
#  googleplus               = "//google.com/you"
#  twitter                  = "//twitter.com/you" 
#  px500                    = "//px500"
#  instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
    

  firstName = "Lee"
    lastName = "Frank"
    address = "Shenyang, CN"
    phone = "13478875695"
    contactNote = "DevOps Engineer"
