baseURL = "https://www.easyolap.cn"
languageCode = "zh"
title = "Eddie Webb"
theme = "hugo-resume"



[author]
  name = "¿Ó‘⁄≥¨"
  homepage = "https://www.easyolap.cn"


[original]
  name = "Start Bootstrap Resume"
  homepage = "https://startbootstrap.com/template-overviews/resume/"
  repo = "https://github.com/BlackrockDigital/startbootstrap-resume"
  
[params]
    firstName = "Lee"
    lastName = "Frank"
    address = "Shenyang, CN"
    phone = "13478875695"
    contactNote = "DevOps Engineer"
    profileImage = "img/TechChat.jpg"
    email = "surpass_li@aliyun.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/frank-li-a109b65a/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/surpass/"
